/*
  Warnings:

  - The values [ACCOUNT_DEACTIVATION,ACCOUNT_DELETION] on the enum `SecurityEventType` will be removed. If these variants are still used in the database, this will fail.

*/
-- AlterEnum
BEGIN;
CREATE TYPE "SecurityEventType_new" AS ENUM ('LOGIN_ATTEMPT', 'LOGIN_SUCCESS', 'LOGIN_FAILURE', 'PASSWORD_RESET_REQUEST', 'PASSWORD_RESET_SUCCESS', 'PASSWORD_RESET_FAILURE', 'PASSWORD_CHANGE_REQUEST', 'PASSWORD_CHANGE_SUCCESS', 'PASSWORD_CHANGE_FAILURE', 'EMAIL_VERIFICATION', 'EMAIL_VERIFICATION_SUCCESS', 'EMAIL_VERIFICATION_FAILURE', 'ACCOUNT_LOCKED', 'SUSPICIOUS_ACTIVITY', 'ACCOUNT_DEACTIVATION_SUCCESS', 'ACCOUNT_DEACTIVATION_FAILURE', 'ACCOUNT_DELETION_SUCCESS', 'ACCOUNT_DELETION_FAILURE', 'LOGOUT_ATTEMPT', 'LOGOUT_SUCCESS', 'LOGOUT_FAILURE', 'SERVICE_AUTH_SUCCESS', 'SERVICE_AUTH_FAILURE', 'EMAIL_UPDATE_SUCCESS', 'EMAIL_UPDATE_FAILURE', 'PHONE_UPDATE_SUCCESS', 'PHONE_UPDATE_FAILURE');
ALTER TABLE "security_logs" ALTER COLUMN "eventType" TYPE "SecurityEventType_new" USING ("eventType"::text::"SecurityEventType_new");
ALTER TYPE "SecurityEventType" RENAME TO "SecurityEventType_old";
ALTER TYPE "SecurityEventType_new" RENAME TO "SecurityEventType";
DROP TYPE "SecurityEventType_old";
COMMIT;
