openapi: 3.0.0
paths:
  /api/auth/health:
    get:
      summary: Auth service health check
      tags:
        - Auth
      responses:
        "200":
          description: Auth service is healthy
          content:
            application/json:
              schema:
                type: object
                properties:
                  service:
                    type: string
                    example: auth
                  route:
                    type: string
                    example: auth
                  status:
                    type: string
                    example: healthy
                  timestamp:
                    type: string
                    format: date-time

  /api/auth/signup:
    post:
      summary: Sign up
      tags:
        - Auth
      description: Create a new user account
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
                - number
              properties:
                email:
                  type: string
                  format: email
                  example: user@example.com
                password:
                  type: string
                  format: password
                  example: SecurePass123!
                number:
                  type: string
                  example: "+919876543210"
      responses:
        "201":
          description: User created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: User created successfully. Please verify your email.
                  data:
                    type: object
                    properties:
                      userId:
                        type: string
                        example: user_abc123
                      email:
                        type: string
                        example: user@example.com
                      emailVerified:
                        type: boolean
                        example: false
        "400":
          description: Validation error
        "429":
          description: Rate limit exceeded (3 requests per hour)

  /api/auth/signin:
    post:
      summary: Sign in
      tags:
        - Auth
      description: Authenticate user and create session
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
              properties:
                email:
                  type: string
                  example: user@example.com
                password:
                  type: string
                  example: SecurePass123!
      responses:
        "200":
          description: Signin successful
          headers:
            Set-Cookie:
              schema:
                type: string
                example: session=<session-token>; HttpOnly; Secure; SameSite=Strict
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: Signin successful
                  data:
                    type: object
                    properties:
                      user:
                        type: object
                        properties:
                          userId:
                            type: string
                          email:
                            type: string
                          emailVerified:
                            type: boolean
                          role:
                            type: string
                      session:
                        type: object
                        properties:
                          sessionId:
                            type: string
                          expiresAt:
                            type: string
                            format: date-time
        "401":
          description: Invalid credentials
        "429":
          description: Rate limit exceeded (3 requests per 15 minutes)

  /api/auth/verify-email:
    get:
      summary: Email verification
      tags:
        - Auth
      description: Verify user's email address
      parameters:
        - in: query
          name: token
          required: true
          schema:
            type: string
          description: Email verification token
      responses:
        "200":
          description: Email verified successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: Email verified successfully
                  data:
                    type: object
                    properties:
                      emailVerified:
                        type: boolean
                        example: true
        "400":
          description: Invalid or expired token
        "429":
          description: Rate limit exceeded (5 requests per 15 minutes)

  /api/auth/request-reset:
    post:
      summary: Request password reset
      tags:
        - Auth
      description: Request password reset link
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
              properties:
                email:
                  type: string
                  example: user@example.com
      responses:
        "200":
          description: Password reset email sent
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: Password reset email sent
                  data:
                    type: object
                    properties:
                      email:
                        type: string
                        example: user@example.com
        "429":
          description: Rate limit exceeded (3 requests per hour)

  /api/auth/reset-password:
    post:
      summary: Reset password
      tags:
        - Auth
      description: Reset password using reset token
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - token
                - newPassword
              properties:
                token:
                  type: string
                  description: Password reset token
                newPassword:
                  type: string
                  format: password
                  example: NewSecurePass123!
      responses:
        "200":
          description: Password reset successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: Password reset successful
                  data:
                    type: object
                    properties:
                      passwordReset:
                        type: boolean
                        example: true
        "400":
          description: Invalid or expired token
        "429":
          description: Rate limit exceeded (3 requests per hour)

  /api/auth/change-password:
    post:
      summary: Change password
      tags:
        - Auth
      description: Change password for authenticated user
      security:
        - cookieAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - currentPassword
                - newPassword
              properties:
                currentPassword:
                  type: string
                  format: password
                  example: OldPass123!
                newPassword:
                  type: string
                  format: password
                  example: NewSecurePass123!
      responses:
        "200":
          description: Password changed successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: Password changed successfully
                  data:
                    type: object
                    properties:
                      passwordChanged:
                        type: boolean
                        example: true
        "401":
          description: Unauthorized or invalid current password
        "429":
          description: Rate limit exceeded (50 requests per 15 minutes)

  /api/auth/request-email-verification:
    post:
      summary: Request email verification
      tags:
        - Auth
      description: Request new email verification link
      security:
        - cookieAuth: []
      responses:
        "200":
          description: Verification email sent
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: Verification email sent
                  data:
                    type: object
                    properties:
                      email:
                        type: string
                        example: user@example.com
        "401":
          description: Unauthorized
        "429":
          description: Rate limit exceeded (50 requests per 15 minutes)

  /api/auth/signout:
    post:
      summary: Sign out
      tags:
        - Auth
      description: End user session
      security:
        - cookieAuth: []
      responses:
        "200":
          description: Signout successful
          headers:
            Set-Cookie:
              schema:
                type: string
                example: session=; Max-Age=0
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: Signout successful
                  data:
                    type: object
                    properties:
                      signedOut:
                        type: boolean
                        example: true

  /api/auth/security-info:
    get:
      summary: Get security info
      tags:
        - Auth
      description: Get user's security information
      security:
        - cookieAuth: []
      responses:
        "200":
          description: Security information retrieved
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: Security information retrieved
                  data:
                    type: object
                    properties:
                      twoFactorEnabled:
                        type: boolean
                        example: false
                      lastPasswordChange:
                        type: string
                        format: date-time
                        example: "2025-11-04T10:30:00.000Z"
                      activeSessions:
                        type: integer
                        example: 2
        "401":
          description: Unauthorized

  /api/auth/sessions:
    get:
      summary: Get sessions
      tags:
        - Auth
      description: Get all active sessions for user
      security:
        - cookieAuth: []
      responses:
        "200":
          description: Sessions retrieved
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: Sessions retrieved
                  data:
                    type: object
                    properties:
                      sessions:
                        type: array
                        items:
                          type: object
                          properties:
                            sessionId:
                              type: string
                              example: session_xyz789
                            device:
                              type: string
                              example: Chrome on Windows
                            ipAddress:
                              type: string
                              example: 192.168.1.1
                            lastActive:
                              type: string
                              format: date-time
                            current:
                              type: boolean
                              example: true
        "401":
          description: Unauthorized

  /api/auth/sessions/{sessionId}:
    delete:
      summary: Delete session
      tags:
        - Auth
      description: Terminate a specific session
      security:
        - cookieAuth: []
      parameters:
        - in: path
          name: sessionId
          required: true
          schema:
            type: string
          description: Session ID to delete
          example: session_xyz789
      responses:
        "200":
          description: Session deleted successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: Session deleted successfully
                  data:
                    type: object
                    properties:
                      sessionId:
                        type: string
                        example: session_xyz789
                      deleted:
                        type: boolean
                        example: true
        "401":
          description: Unauthorized
        "404":
          description: Session not found
