openapi: 3.0.0
paths:
  /api/auth/account/health:
    get:
      summary: Account service health check
      tags:
        - Account
      responses:
        "200":
          description: Service is healthy
          content:
            application/json:
              schema:
                type: object
                properties:
                  service:
                    type: string
                    example: user-account-actions
                  status:
                    type: string
                    example: healthy
                  timestamp:
                    type: string
                    format: date-time

  /api/auth/account/me:
    get:
      summary: Get current user profile
      tags:
        - Account
      parameters:
        - in: header
          name: x-service-id
          required: true
          schema:
            type: string
          description: Service identifier
          example: wallet-service
        - in: header
          name: x-service-secret
          required: true
          schema:
            type: string
          description: Service secret key
        - in: header
          name: x-user-id
          required: true
          schema:
            type: integer
          description: User ID
          example: 123
      responses:
        "200":
          description: User profile retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: User profile retrieved successfully
                  data:
                    type: object
                    properties:
                      user:
                        type: object
                        properties:
                          id:
                            type: integer
                            example: 123
                          email:
                            type: string
                            example: john@example.com
                          number:
                            type: string
                            example: "1234567890"
                          walletID:
                            type: string
                            example: wallet_abc123
                          emailVerified:
                            type: boolean
                            example: true
                          isActive:
                            type: boolean
                            example: true
                          role:
                            type: string
                            example: USER
                          createdAt:
                            type: string
                            format: date-time
                          lastLoginAt:
                            type: string
                            format: date-time
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  message:
                    type: string
                    example: "Unauthorized: User info missing"
                  error:
                    type: object
                    properties:
                      code:
                        type: string
                        example: AUTHENTICATION
                      type:
                        type: string
                        example: AUTHENTICATION_ERROR
                      details:
                        type: string
                        example: User ID not found in request

  /api/auth/account/update-user:
    post:
      summary: Update user details
      tags:
        - Account
      parameters:
        - in: header
          name: x-service-id
          required: true
          schema:
            type: string
          description: Service identifier
          example: wallet-service
        - in: header
          name: x-service-secret
          required: true
          schema:
            type: string
          description: Service secret key
        - in: header
          name: x-user-id
          required: true
          schema:
            type: integer
          description: User ID
          example: 123
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: John Updated Doe
                address:
                  type: string
                  example: 123 Main St
                country:
                  type: string
                  example: USA
                state:
                  type: string
                  example: California
                dob:
                  type: string
                  format: date
                  example: "1990-01-01"
      responses:
        "200":
          description: User updated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: Successfully updated 5 field(s)
                  data:
                    type: object
                    properties:
                      user:
                        type: object
                        properties:
                          id:
                            type: integer
                          email:
                            type: string
                          number:
                            type: string
                          walletID:
                            type: string
                          name:
                            type: string
                          address:
                            type: string
                          country:
                            type: string
                          state:
                            type: string
                          dob:
                            type: string
                            format: date-time
                          emailVerified:
                            type: boolean
                          isActive:
                            type: boolean
                          role:
                            type: string
                          createdAt:
                            type: string
                            format: date-time
                          lastLoginAt:
                            type: string
                            format: date-time
                  metadata:
                    type: object
                    properties:
                      summary:
                        type: object
                        properties:
                          totalFields:
                            type: integer
                            example: 5
                          updatedFields:
                            type: integer
                            example: 5
                          rejectedFields:
                            type: integer
                            example: 0
                          validationErrors:
                            type: integer
                            example: 0
        "400":
          description: Invalid input
        "401":
          description: Unauthorized
        "403":
          description: Account inactive
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  message:
                    type: string
                    example: Account is inactive
                  error:
                    type: object
                    properties:
                      code:
                        type: string
                        example: AUTHORIZATION
                      type:
                        type: string
                        example: AUTHORIZATION_ERROR
                      details:
                        type: string
                        example: This account has been deactivated
