apiVersion: v1
kind: Service
metadata:
  name: transaction-service
  namespace: swiftpay
spec:
  type: ClusterIP
  selector:
    app: transaction-service
  ports:
    - port: 5003
      targetPort: 5003
